### ISSUE TITLE
Step 3: 👍 Choose a project & create a Vision Statement

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v40-bears-team-33#8]
From voyage-template created by [jdmedlock](https://github.com/jdmedlock): chingu-voyages/voyage-template#7  

**__Task Description__**
- [x] Watch the [How to Select a Voyage Project](https://youtu.be/5Xv0C5VAKZc) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/5Xv0C5VAKZc)
- [x] Collect ideas from the team
- [x] Brainstorm with your team
- [x] Vote to select one idea
- [x] Decide on the technical stack you’ll use to build your project

**__Technical Considerations__**
N/a

**__Additional Considerations__**
Use the [Project Vision and Feature Planning template](https://docs.google.com/document/d/1pG-6ihL47P6IpMtcgVeb5_DWoatZcsMTwx_lGDmfh9o/edit?usp=sharing) to gather & vote on everyone's idea

**__Resources__**
[Choose a Project & create a Vision Statement (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#f98c81e380cd47819e6a5072e017d17b)

**Member of Epic:** #16

**Comment by AlvarezJaimeR** [comment]
Payup -- betting app with a twist. you don't bet on teams. you bet on yourself! Users place a wager, they pay up. upon challenge/game/tournament completion the winner receives the funds. No IOU's and no worries about the other person not paying up. 
Tech stack -- PERN hosted on Heroku.
